// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Store.Infrastructure.Repository.DbContexts;

#nullable disable

namespace Store.Infrastructure.Migrations.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20230511005619_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("StoreDb")
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 30);

            modelBuilder.Entity("Store.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .HasColumnType("nclob");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nclob");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal");

                    b.Property<byte>("RecordStatus")
                        .HasColumnType("byte");

                    b.HasKey("Id");

                    b.ToTable("Product", "StoreDb");
                });
#pragma warning restore 612, 618
        }
    }
}
